const person1 = 'how are you';
const person2 = "i am fine and you";
const person3 = `hello world`;
console.log(person1);
console.log(person2);
console.log(person3);
const name = 'arafat';
const age = 22;
const country = 'bangladesh';
const string = `my name is ${name}. i am ${age} years old. i am from ${country}.`;
console.log(string);